title: Node.js support
author: George Daniels
email: geodin_2000@yahoo.com
description: > # this is for the resources needed to run Node.js and receive help with your code

# social links
twitter_username: your-twitter-handle
github_username:  geodin2019

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
